// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAuVeMJQsrdsAPg9xRTsuitWY9WfYq4fA',
    appId: '1:44921930608:web:a4c9b29b45276cc26285b5',
    messagingSenderId: '44921930608',
    projectId: 'expanded-curve-254717',
    authDomain: 'expanded-curve-254717.firebaseapp.com',
    storageBucket: 'expanded-curve-254717.appspot.com',
    measurementId: 'G-R6TGKCWWQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiOKwxjjEnQrZewBsbr1Y5vq0fBvij9s',
    appId: '1:44921930608:android:dd81066209594f496285b5',
    messagingSenderId: '44921930608',
    projectId: 'expanded-curve-254717',
    storageBucket: 'expanded-curve-254717.appspot.com',
  );
}
